import Layout1 from "@/components/Layout1";
// import "@/styles/globals.css";
import { NextComponentType, NextPageContext } from "next";
import type { AppProps } from "next/app";
import Head from "next/head";

interface ComponentWithTitle extends AppProps {
  Component: NextComponentType<NextPageContext, any, any> & {
    title?: string
  };
}
export default function App({ Component, pageProps }: ComponentWithTitle) {
  return (
    <>
      <Head>
        <title>{Component.title ?? "The good corner"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout1>
        <Component {...pageProps} />
      </Layout1>
    </>
  );
}